name: nae-entertainment

services:
  backend:
    build:
      context: ./be
    container_name: nae-backend
    ports:
      - "4000:4000"
    volumes:
      - ./be/data:/app/data
      - ./be/public:/app/public
    env_file:
      - ./be/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./fe
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_API_KEY=${VITE_API_KEY}
        - VITE_YOUTUBE_API_KEY=${VITE_YOUTUBE_API_KEY}
        - VITE_YOUTUBE_CHANNEL_ID=${VITE_YOUTUBE_CHANNEL_ID}
        - VITE_YOUTUBE_USERNAME=${VITE_YOUTUBE_USERNAME}
    container_name: nae-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
